# Generated by Django 2.2.3 on 2019-08-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=19200, null=True),
        ),
    ]
